image: Visual Studio 2019

build_script:
  - ps: dotnet build src/VSSDK.Helpers.15.0/VSSDK.Helpers.15.0.csproj /p:configuration=Release /p:Version=15.0.$($env:appveyor_build_number)
  - ps: dotnet build src/VSSDK.Helpers.16.0/VSSDK.Helpers.16.0.csproj /p:configuration=Release /p:Version=16.0.$($env:appveyor_build_number)

artifacts:
  - path: src\**\*.nupkg
    name: NuGet package

  - path: src\**\*.snupkg
    name: Symbol package

deploy:
  - provider: NuGet
    artifact: /NuGet/
    api_key:
      secure: 2LiTL6oY/0UkItVFZDP+iQqDsLl9BK9yM4rMyvbB9pL+/bXzzaerqFhR6NRmhRbs
    on:
      branch: master
      appveyor_repo_commit_message_extended: /\[release\]/
